### ISSUE TITLE
Update to v4.0

### ISSUE THREAD

**Issue by karmanyaahm** [aerfanr/fedora-33-kde-dynamic-wallpaper#1]
Hi,
There is a new version of the dynamic wallpaper engine that uses a new wallpaper format. It would be great if you can check out the release notes and update this wallpaper: https://github.com/zzag/plasma5-wallpapers-dynamic/releases/tag/4.0.0

**Comment by aerfanr** [comment]
Hello there.
Sorry I did not read this issue soon enough.
From my understanding, I just need to run the wallpaper creator and make a new release. I will do that as soon as I can.
Thanks
